# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/somebody/B-CPP-500-COT-5-1-rtype-jaures.agossou

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/somebody/B-CPP-500-COT-5-1-rtype-jaures.agossou

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/somebody/B-CPP-500-COT-5-1-rtype-jaures.agossou/CMakeFiles /home/somebody/B-CPP-500-COT-5-1-rtype-jaures.agossou//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/somebody/B-CPP-500-COT-5-1-rtype-jaures.agossou/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named r-type_server

# Build rule for target.
r-type_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_server
.PHONY : r-type_server

# fast build rule for target.
r-type_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/build
.PHONY : r-type_server/fast

#=============================================================================
# Target rules for targets named r-type_client

# Build rule for target.
r-type_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_client
.PHONY : r-type_client

# fast build rule for target.
r-type_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/build
.PHONY : r-type_client/fast

Client/src/AssetManager.o: Client/src/AssetManager.cpp.o
.PHONY : Client/src/AssetManager.o

# target to build an object file
Client/src/AssetManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/AssetManager.cpp.o
.PHONY : Client/src/AssetManager.cpp.o

Client/src/AssetManager.i: Client/src/AssetManager.cpp.i
.PHONY : Client/src/AssetManager.i

# target to preprocess a source file
Client/src/AssetManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/AssetManager.cpp.i
.PHONY : Client/src/AssetManager.cpp.i

Client/src/AssetManager.s: Client/src/AssetManager.cpp.s
.PHONY : Client/src/AssetManager.s

# target to generate assembly for a file
Client/src/AssetManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/AssetManager.cpp.s
.PHONY : Client/src/AssetManager.cpp.s

Client/src/NameEntryScreen.o: Client/src/NameEntryScreen.cpp.o
.PHONY : Client/src/NameEntryScreen.o

# target to build an object file
Client/src/NameEntryScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/NameEntryScreen.cpp.o
.PHONY : Client/src/NameEntryScreen.cpp.o

Client/src/NameEntryScreen.i: Client/src/NameEntryScreen.cpp.i
.PHONY : Client/src/NameEntryScreen.i

# target to preprocess a source file
Client/src/NameEntryScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/NameEntryScreen.cpp.i
.PHONY : Client/src/NameEntryScreen.cpp.i

Client/src/NameEntryScreen.s: Client/src/NameEntryScreen.cpp.s
.PHONY : Client/src/NameEntryScreen.s

# target to generate assembly for a file
Client/src/NameEntryScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/NameEntryScreen.cpp.s
.PHONY : Client/src/NameEntryScreen.cpp.s

Client/src/NetworkEntityMapper.o: Client/src/NetworkEntityMapper.cpp.o
.PHONY : Client/src/NetworkEntityMapper.o

# target to build an object file
Client/src/NetworkEntityMapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/NetworkEntityMapper.cpp.o
.PHONY : Client/src/NetworkEntityMapper.cpp.o

Client/src/NetworkEntityMapper.i: Client/src/NetworkEntityMapper.cpp.i
.PHONY : Client/src/NetworkEntityMapper.i

# target to preprocess a source file
Client/src/NetworkEntityMapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/NetworkEntityMapper.cpp.i
.PHONY : Client/src/NetworkEntityMapper.cpp.i

Client/src/NetworkEntityMapper.s: Client/src/NetworkEntityMapper.cpp.s
.PHONY : Client/src/NetworkEntityMapper.s

# target to generate assembly for a file
Client/src/NetworkEntityMapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/NetworkEntityMapper.cpp.s
.PHONY : Client/src/NetworkEntityMapper.cpp.s

Client/src/Replay.o: Client/src/Replay.cpp.o
.PHONY : Client/src/Replay.o

# target to build an object file
Client/src/Replay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/Replay.cpp.o
.PHONY : Client/src/Replay.cpp.o

Client/src/Replay.i: Client/src/Replay.cpp.i
.PHONY : Client/src/Replay.i

# target to preprocess a source file
Client/src/Replay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/Replay.cpp.i
.PHONY : Client/src/Replay.cpp.i

Client/src/Replay.s: Client/src/Replay.cpp.s
.PHONY : Client/src/Replay.s

# target to generate assembly for a file
Client/src/Replay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/Replay.cpp.s
.PHONY : Client/src/Replay.cpp.s

Client/src/SoloPlay.o: Client/src/SoloPlay.cpp.o
.PHONY : Client/src/SoloPlay.o

# target to build an object file
Client/src/SoloPlay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/SoloPlay.cpp.o
.PHONY : Client/src/SoloPlay.cpp.o

Client/src/SoloPlay.i: Client/src/SoloPlay.cpp.i
.PHONY : Client/src/SoloPlay.i

# target to preprocess a source file
Client/src/SoloPlay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/SoloPlay.cpp.i
.PHONY : Client/src/SoloPlay.cpp.i

Client/src/SoloPlay.s: Client/src/SoloPlay.cpp.s
.PHONY : Client/src/SoloPlay.s

# target to generate assembly for a file
Client/src/SoloPlay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/SoloPlay.cpp.s
.PHONY : Client/src/SoloPlay.cpp.s

Client/src/SoundManager.o: Client/src/SoundManager.cpp.o
.PHONY : Client/src/SoundManager.o

# target to build an object file
Client/src/SoundManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/SoundManager.cpp.o
.PHONY : Client/src/SoundManager.cpp.o

Client/src/SoundManager.i: Client/src/SoundManager.cpp.i
.PHONY : Client/src/SoundManager.i

# target to preprocess a source file
Client/src/SoundManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/SoundManager.cpp.i
.PHONY : Client/src/SoundManager.cpp.i

Client/src/SoundManager.s: Client/src/SoundManager.cpp.s
.PHONY : Client/src/SoundManager.s

# target to generate assembly for a file
Client/src/SoundManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/SoundManager.cpp.s
.PHONY : Client/src/SoundManager.cpp.s

Client/src/client.o: Client/src/client.cpp.o
.PHONY : Client/src/client.o

# target to build an object file
Client/src/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client.cpp.o
.PHONY : Client/src/client.cpp.o

Client/src/client.i: Client/src/client.cpp.i
.PHONY : Client/src/client.i

# target to preprocess a source file
Client/src/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client.cpp.i
.PHONY : Client/src/client.cpp.i

Client/src/client.s: Client/src/client.cpp.s
.PHONY : Client/src/client.s

# target to generate assembly for a file
Client/src/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client.cpp.s
.PHONY : Client/src/client.cpp.s

Client/src/client2.o: Client/src/client2.cpp.o
.PHONY : Client/src/client2.o

# target to build an object file
Client/src/client2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client2.cpp.o
.PHONY : Client/src/client2.cpp.o

Client/src/client2.i: Client/src/client2.cpp.i
.PHONY : Client/src/client2.i

# target to preprocess a source file
Client/src/client2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client2.cpp.i
.PHONY : Client/src/client2.cpp.i

Client/src/client2.s: Client/src/client2.cpp.s
.PHONY : Client/src/client2.s

# target to generate assembly for a file
Client/src/client2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client2.cpp.s
.PHONY : Client/src/client2.cpp.s

Client/src/client_init.o: Client/src/client_init.cpp.o
.PHONY : Client/src/client_init.o

# target to build an object file
Client/src/client_init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_init.cpp.o
.PHONY : Client/src/client_init.cpp.o

Client/src/client_init.i: Client/src/client_init.cpp.i
.PHONY : Client/src/client_init.i

# target to preprocess a source file
Client/src/client_init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_init.cpp.i
.PHONY : Client/src/client_init.cpp.i

Client/src/client_init.s: Client/src/client_init.cpp.s
.PHONY : Client/src/client_init.s

# target to generate assembly for a file
Client/src/client_init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_init.cpp.s
.PHONY : Client/src/client_init.cpp.s

Client/src/client_network_part_one.o: Client/src/client_network_part_one.cpp.o
.PHONY : Client/src/client_network_part_one.o

# target to build an object file
Client/src/client_network_part_one.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_network_part_one.cpp.o
.PHONY : Client/src/client_network_part_one.cpp.o

Client/src/client_network_part_one.i: Client/src/client_network_part_one.cpp.i
.PHONY : Client/src/client_network_part_one.i

# target to preprocess a source file
Client/src/client_network_part_one.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_network_part_one.cpp.i
.PHONY : Client/src/client_network_part_one.cpp.i

Client/src/client_network_part_one.s: Client/src/client_network_part_one.cpp.s
.PHONY : Client/src/client_network_part_one.s

# target to generate assembly for a file
Client/src/client_network_part_one.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_network_part_one.cpp.s
.PHONY : Client/src/client_network_part_one.cpp.s

Client/src/client_network_part_two.o: Client/src/client_network_part_two.cpp.o
.PHONY : Client/src/client_network_part_two.o

# target to build an object file
Client/src/client_network_part_two.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_network_part_two.cpp.o
.PHONY : Client/src/client_network_part_two.cpp.o

Client/src/client_network_part_two.i: Client/src/client_network_part_two.cpp.i
.PHONY : Client/src/client_network_part_two.i

# target to preprocess a source file
Client/src/client_network_part_two.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_network_part_two.cpp.i
.PHONY : Client/src/client_network_part_two.cpp.i

Client/src/client_network_part_two.s: Client/src/client_network_part_two.cpp.s
.PHONY : Client/src/client_network_part_two.s

# target to generate assembly for a file
Client/src/client_network_part_two.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_network_part_two.cpp.s
.PHONY : Client/src/client_network_part_two.cpp.s

Client/src/client_protocol.o: Client/src/client_protocol.cpp.o
.PHONY : Client/src/client_protocol.o

# target to build an object file
Client/src/client_protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_protocol.cpp.o
.PHONY : Client/src/client_protocol.cpp.o

Client/src/client_protocol.i: Client/src/client_protocol.cpp.i
.PHONY : Client/src/client_protocol.i

# target to preprocess a source file
Client/src/client_protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_protocol.cpp.i
.PHONY : Client/src/client_protocol.cpp.i

Client/src/client_protocol.s: Client/src/client_protocol.cpp.s
.PHONY : Client/src/client_protocol.s

# target to generate assembly for a file
Client/src/client_protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_protocol.cpp.s
.PHONY : Client/src/client_protocol.cpp.s

Client/src/client_replay.o: Client/src/client_replay.cpp.o
.PHONY : Client/src/client_replay.o

# target to build an object file
Client/src/client_replay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_replay.cpp.o
.PHONY : Client/src/client_replay.cpp.o

Client/src/client_replay.i: Client/src/client_replay.cpp.i
.PHONY : Client/src/client_replay.i

# target to preprocess a source file
Client/src/client_replay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_replay.cpp.i
.PHONY : Client/src/client_replay.cpp.i

Client/src/client_replay.s: Client/src/client_replay.cpp.s
.PHONY : Client/src/client_replay.s

# target to generate assembly for a file
Client/src/client_replay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_replay.cpp.s
.PHONY : Client/src/client_replay.cpp.s

Client/src/client_update.o: Client/src/client_update.cpp.o
.PHONY : Client/src/client_update.o

# target to build an object file
Client/src/client_update.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_update.cpp.o
.PHONY : Client/src/client_update.cpp.o

Client/src/client_update.i: Client/src/client_update.cpp.i
.PHONY : Client/src/client_update.i

# target to preprocess a source file
Client/src/client_update.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_update.cpp.i
.PHONY : Client/src/client_update.cpp.i

Client/src/client_update.s: Client/src/client_update.cpp.s
.PHONY : Client/src/client_update.s

# target to generate assembly for a file
Client/src/client_update.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/client_update.cpp.s
.PHONY : Client/src/client_update.cpp.s

Client/src/main.o: Client/src/main.cpp.o
.PHONY : Client/src/main.o

# target to build an object file
Client/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/main.cpp.o
.PHONY : Client/src/main.cpp.o

Client/src/main.i: Client/src/main.cpp.i
.PHONY : Client/src/main.i

# target to preprocess a source file
Client/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/main.cpp.i
.PHONY : Client/src/main.cpp.i

Client/src/main.s: Client/src/main.cpp.s
.PHONY : Client/src/main.s

# target to generate assembly for a file
Client/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/main.cpp.s
.PHONY : Client/src/main.cpp.s

Client/src/solo_play_render.o: Client/src/solo_play_render.cpp.o
.PHONY : Client/src/solo_play_render.o

# target to build an object file
Client/src/solo_play_render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/solo_play_render.cpp.o
.PHONY : Client/src/solo_play_render.cpp.o

Client/src/solo_play_render.i: Client/src/solo_play_render.cpp.i
.PHONY : Client/src/solo_play_render.i

# target to preprocess a source file
Client/src/solo_play_render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/solo_play_render.cpp.i
.PHONY : Client/src/solo_play_render.cpp.i

Client/src/solo_play_render.s: Client/src/solo_play_render.cpp.s
.PHONY : Client/src/solo_play_render.s

# target to generate assembly for a file
Client/src/solo_play_render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Client/src/solo_play_render.cpp.s
.PHONY : Client/src/solo_play_render.cpp.s

Core/src/Core.o: Core/src/Core.cpp.o
.PHONY : Core/src/Core.o

# target to build an object file
Core/src/Core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Core/src/Core.cpp.o
.PHONY : Core/src/Core.cpp.o

Core/src/Core.i: Core/src/Core.cpp.i
.PHONY : Core/src/Core.i

# target to preprocess a source file
Core/src/Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Core/src/Core.cpp.i
.PHONY : Core/src/Core.cpp.i

Core/src/Core.s: Core/src/Core.cpp.s
.PHONY : Core/src/Core.s

# target to generate assembly for a file
Core/src/Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Core/src/Core.cpp.s
.PHONY : Core/src/Core.cpp.s

GameEngine/src/AnimationSystem.o: GameEngine/src/AnimationSystem.cpp.o
.PHONY : GameEngine/src/AnimationSystem.o

# target to build an object file
GameEngine/src/AnimationSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/AnimationSystem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/AnimationSystem.cpp.o
.PHONY : GameEngine/src/AnimationSystem.cpp.o

GameEngine/src/AnimationSystem.i: GameEngine/src/AnimationSystem.cpp.i
.PHONY : GameEngine/src/AnimationSystem.i

# target to preprocess a source file
GameEngine/src/AnimationSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/AnimationSystem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/AnimationSystem.cpp.i
.PHONY : GameEngine/src/AnimationSystem.cpp.i

GameEngine/src/AnimationSystem.s: GameEngine/src/AnimationSystem.cpp.s
.PHONY : GameEngine/src/AnimationSystem.s

# target to generate assembly for a file
GameEngine/src/AnimationSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/AnimationSystem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/AnimationSystem.cpp.s
.PHONY : GameEngine/src/AnimationSystem.cpp.s

GameEngine/src/BossSystem.o: GameEngine/src/BossSystem.cpp.o
.PHONY : GameEngine/src/BossSystem.o

# target to build an object file
GameEngine/src/BossSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/BossSystem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/BossSystem.cpp.o
.PHONY : GameEngine/src/BossSystem.cpp.o

GameEngine/src/BossSystem.i: GameEngine/src/BossSystem.cpp.i
.PHONY : GameEngine/src/BossSystem.i

# target to preprocess a source file
GameEngine/src/BossSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/BossSystem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/BossSystem.cpp.i
.PHONY : GameEngine/src/BossSystem.cpp.i

GameEngine/src/BossSystem.s: GameEngine/src/BossSystem.cpp.s
.PHONY : GameEngine/src/BossSystem.s

# target to generate assembly for a file
GameEngine/src/BossSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/BossSystem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/BossSystem.cpp.s
.PHONY : GameEngine/src/BossSystem.cpp.s

GameEngine/src/CollectableSystem.o: GameEngine/src/CollectableSystem.cpp.o
.PHONY : GameEngine/src/CollectableSystem.o

# target to build an object file
GameEngine/src/CollectableSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/CollectableSystem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/CollectableSystem.cpp.o
.PHONY : GameEngine/src/CollectableSystem.cpp.o

GameEngine/src/CollectableSystem.i: GameEngine/src/CollectableSystem.cpp.i
.PHONY : GameEngine/src/CollectableSystem.i

# target to preprocess a source file
GameEngine/src/CollectableSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/CollectableSystem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/CollectableSystem.cpp.i
.PHONY : GameEngine/src/CollectableSystem.cpp.i

GameEngine/src/CollectableSystem.s: GameEngine/src/CollectableSystem.cpp.s
.PHONY : GameEngine/src/CollectableSystem.s

# target to generate assembly for a file
GameEngine/src/CollectableSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/CollectableSystem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/CollectableSystem.cpp.s
.PHONY : GameEngine/src/CollectableSystem.cpp.s

GameEngine/src/CollisionSystem.o: GameEngine/src/CollisionSystem.cpp.o
.PHONY : GameEngine/src/CollisionSystem.o

# target to build an object file
GameEngine/src/CollisionSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/CollisionSystem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/CollisionSystem.cpp.o
.PHONY : GameEngine/src/CollisionSystem.cpp.o

GameEngine/src/CollisionSystem.i: GameEngine/src/CollisionSystem.cpp.i
.PHONY : GameEngine/src/CollisionSystem.i

# target to preprocess a source file
GameEngine/src/CollisionSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/CollisionSystem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/CollisionSystem.cpp.i
.PHONY : GameEngine/src/CollisionSystem.cpp.i

GameEngine/src/CollisionSystem.s: GameEngine/src/CollisionSystem.cpp.s
.PHONY : GameEngine/src/CollisionSystem.s

# target to generate assembly for a file
GameEngine/src/CollisionSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/CollisionSystem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/CollisionSystem.cpp.s
.PHONY : GameEngine/src/CollisionSystem.cpp.s

GameEngine/src/ComponentManager.o: GameEngine/src/ComponentManager.cpp.o
.PHONY : GameEngine/src/ComponentManager.o

# target to build an object file
GameEngine/src/ComponentManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/ComponentManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/ComponentManager.cpp.o
.PHONY : GameEngine/src/ComponentManager.cpp.o

GameEngine/src/ComponentManager.i: GameEngine/src/ComponentManager.cpp.i
.PHONY : GameEngine/src/ComponentManager.i

# target to preprocess a source file
GameEngine/src/ComponentManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/ComponentManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/ComponentManager.cpp.i
.PHONY : GameEngine/src/ComponentManager.cpp.i

GameEngine/src/ComponentManager.s: GameEngine/src/ComponentManager.cpp.s
.PHONY : GameEngine/src/ComponentManager.s

# target to generate assembly for a file
GameEngine/src/ComponentManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/ComponentManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/ComponentManager.cpp.s
.PHONY : GameEngine/src/ComponentManager.cpp.s

GameEngine/src/EnemyBulletSystem.o: GameEngine/src/EnemyBulletSystem.cpp.o
.PHONY : GameEngine/src/EnemyBulletSystem.o

# target to build an object file
GameEngine/src/EnemyBulletSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/EnemyBulletSystem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/EnemyBulletSystem.cpp.o
.PHONY : GameEngine/src/EnemyBulletSystem.cpp.o

GameEngine/src/EnemyBulletSystem.i: GameEngine/src/EnemyBulletSystem.cpp.i
.PHONY : GameEngine/src/EnemyBulletSystem.i

# target to preprocess a source file
GameEngine/src/EnemyBulletSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/EnemyBulletSystem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/EnemyBulletSystem.cpp.i
.PHONY : GameEngine/src/EnemyBulletSystem.cpp.i

GameEngine/src/EnemyBulletSystem.s: GameEngine/src/EnemyBulletSystem.cpp.s
.PHONY : GameEngine/src/EnemyBulletSystem.s

# target to generate assembly for a file
GameEngine/src/EnemyBulletSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/EnemyBulletSystem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/EnemyBulletSystem.cpp.s
.PHONY : GameEngine/src/EnemyBulletSystem.cpp.s

GameEngine/src/EnemySystem.o: GameEngine/src/EnemySystem.cpp.o
.PHONY : GameEngine/src/EnemySystem.o

# target to build an object file
GameEngine/src/EnemySystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/EnemySystem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/EnemySystem.cpp.o
.PHONY : GameEngine/src/EnemySystem.cpp.o

GameEngine/src/EnemySystem.i: GameEngine/src/EnemySystem.cpp.i
.PHONY : GameEngine/src/EnemySystem.i

# target to preprocess a source file
GameEngine/src/EnemySystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/EnemySystem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/EnemySystem.cpp.i
.PHONY : GameEngine/src/EnemySystem.cpp.i

GameEngine/src/EnemySystem.s: GameEngine/src/EnemySystem.cpp.s
.PHONY : GameEngine/src/EnemySystem.s

# target to generate assembly for a file
GameEngine/src/EnemySystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/EnemySystem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/EnemySystem.cpp.s
.PHONY : GameEngine/src/EnemySystem.cpp.s

GameEngine/src/EntityManager.o: GameEngine/src/EntityManager.cpp.o
.PHONY : GameEngine/src/EntityManager.o

# target to build an object file
GameEngine/src/EntityManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/EntityManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/EntityManager.cpp.o
.PHONY : GameEngine/src/EntityManager.cpp.o

GameEngine/src/EntityManager.i: GameEngine/src/EntityManager.cpp.i
.PHONY : GameEngine/src/EntityManager.i

# target to preprocess a source file
GameEngine/src/EntityManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/EntityManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/EntityManager.cpp.i
.PHONY : GameEngine/src/EntityManager.cpp.i

GameEngine/src/EntityManager.s: GameEngine/src/EntityManager.cpp.s
.PHONY : GameEngine/src/EntityManager.s

# target to generate assembly for a file
GameEngine/src/EntityManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/EntityManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/EntityManager.cpp.s
.PHONY : GameEngine/src/EntityManager.cpp.s

GameEngine/src/GameLogic.o: GameEngine/src/GameLogic.cpp.o
.PHONY : GameEngine/src/GameLogic.o

# target to build an object file
GameEngine/src/GameLogic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/GameLogic.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/GameLogic.cpp.o
.PHONY : GameEngine/src/GameLogic.cpp.o

GameEngine/src/GameLogic.i: GameEngine/src/GameLogic.cpp.i
.PHONY : GameEngine/src/GameLogic.i

# target to preprocess a source file
GameEngine/src/GameLogic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/GameLogic.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/GameLogic.cpp.i
.PHONY : GameEngine/src/GameLogic.cpp.i

GameEngine/src/GameLogic.s: GameEngine/src/GameLogic.cpp.s
.PHONY : GameEngine/src/GameLogic.s

# target to generate assembly for a file
GameEngine/src/GameLogic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/GameLogic.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/GameLogic.cpp.s
.PHONY : GameEngine/src/GameLogic.cpp.s

GameEngine/src/LuaScript.o: GameEngine/src/LuaScript.cpp.o
.PHONY : GameEngine/src/LuaScript.o

# target to build an object file
GameEngine/src/LuaScript.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/LuaScript.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/LuaScript.cpp.o
.PHONY : GameEngine/src/LuaScript.cpp.o

GameEngine/src/LuaScript.i: GameEngine/src/LuaScript.cpp.i
.PHONY : GameEngine/src/LuaScript.i

# target to preprocess a source file
GameEngine/src/LuaScript.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/LuaScript.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/LuaScript.cpp.i
.PHONY : GameEngine/src/LuaScript.cpp.i

GameEngine/src/LuaScript.s: GameEngine/src/LuaScript.cpp.s
.PHONY : GameEngine/src/LuaScript.s

# target to generate assembly for a file
GameEngine/src/LuaScript.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/LuaScript.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/LuaScript.cpp.s
.PHONY : GameEngine/src/LuaScript.cpp.s

GameEngine/src/Mediator.o: GameEngine/src/Mediator.cpp.o
.PHONY : GameEngine/src/Mediator.o

# target to build an object file
GameEngine/src/Mediator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/Mediator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/Mediator.cpp.o
.PHONY : GameEngine/src/Mediator.cpp.o

GameEngine/src/Mediator.i: GameEngine/src/Mediator.cpp.i
.PHONY : GameEngine/src/Mediator.i

# target to preprocess a source file
GameEngine/src/Mediator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/Mediator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/Mediator.cpp.i
.PHONY : GameEngine/src/Mediator.cpp.i

GameEngine/src/Mediator.s: GameEngine/src/Mediator.cpp.s
.PHONY : GameEngine/src/Mediator.s

# target to generate assembly for a file
GameEngine/src/Mediator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/Mediator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/Mediator.cpp.s
.PHONY : GameEngine/src/Mediator.cpp.s

GameEngine/src/MovementSystem.o: GameEngine/src/MovementSystem.cpp.o
.PHONY : GameEngine/src/MovementSystem.o

# target to build an object file
GameEngine/src/MovementSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/MovementSystem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/MovementSystem.cpp.o
.PHONY : GameEngine/src/MovementSystem.cpp.o

GameEngine/src/MovementSystem.i: GameEngine/src/MovementSystem.cpp.i
.PHONY : GameEngine/src/MovementSystem.i

# target to preprocess a source file
GameEngine/src/MovementSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/MovementSystem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/MovementSystem.cpp.i
.PHONY : GameEngine/src/MovementSystem.cpp.i

GameEngine/src/MovementSystem.s: GameEngine/src/MovementSystem.cpp.s
.PHONY : GameEngine/src/MovementSystem.s

# target to generate assembly for a file
GameEngine/src/MovementSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/MovementSystem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/MovementSystem.cpp.s
.PHONY : GameEngine/src/MovementSystem.cpp.s

GameEngine/src/ObstacleSystem.o: GameEngine/src/ObstacleSystem.cpp.o
.PHONY : GameEngine/src/ObstacleSystem.o

# target to build an object file
GameEngine/src/ObstacleSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/ObstacleSystem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/ObstacleSystem.cpp.o
.PHONY : GameEngine/src/ObstacleSystem.cpp.o

GameEngine/src/ObstacleSystem.i: GameEngine/src/ObstacleSystem.cpp.i
.PHONY : GameEngine/src/ObstacleSystem.i

# target to preprocess a source file
GameEngine/src/ObstacleSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/ObstacleSystem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/ObstacleSystem.cpp.i
.PHONY : GameEngine/src/ObstacleSystem.cpp.i

GameEngine/src/ObstacleSystem.s: GameEngine/src/ObstacleSystem.cpp.s
.PHONY : GameEngine/src/ObstacleSystem.s

# target to generate assembly for a file
GameEngine/src/ObstacleSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/ObstacleSystem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/ObstacleSystem.cpp.s
.PHONY : GameEngine/src/ObstacleSystem.cpp.s

GameEngine/src/ProjectileSystem.o: GameEngine/src/ProjectileSystem.cpp.o
.PHONY : GameEngine/src/ProjectileSystem.o

# target to build an object file
GameEngine/src/ProjectileSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/ProjectileSystem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/ProjectileSystem.cpp.o
.PHONY : GameEngine/src/ProjectileSystem.cpp.o

GameEngine/src/ProjectileSystem.i: GameEngine/src/ProjectileSystem.cpp.i
.PHONY : GameEngine/src/ProjectileSystem.i

# target to preprocess a source file
GameEngine/src/ProjectileSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/ProjectileSystem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/ProjectileSystem.cpp.i
.PHONY : GameEngine/src/ProjectileSystem.cpp.i

GameEngine/src/ProjectileSystem.s: GameEngine/src/ProjectileSystem.cpp.s
.PHONY : GameEngine/src/ProjectileSystem.s

# target to generate assembly for a file
GameEngine/src/ProjectileSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/ProjectileSystem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/ProjectileSystem.cpp.s
.PHONY : GameEngine/src/ProjectileSystem.cpp.s

GameEngine/src/Quadtree.o: GameEngine/src/Quadtree.cpp.o
.PHONY : GameEngine/src/Quadtree.o

# target to build an object file
GameEngine/src/Quadtree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/Quadtree.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/Quadtree.cpp.o
.PHONY : GameEngine/src/Quadtree.cpp.o

GameEngine/src/Quadtree.i: GameEngine/src/Quadtree.cpp.i
.PHONY : GameEngine/src/Quadtree.i

# target to preprocess a source file
GameEngine/src/Quadtree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/Quadtree.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/Quadtree.cpp.i
.PHONY : GameEngine/src/Quadtree.cpp.i

GameEngine/src/Quadtree.s: GameEngine/src/Quadtree.cpp.s
.PHONY : GameEngine/src/Quadtree.s

# target to generate assembly for a file
GameEngine/src/Quadtree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/Quadtree.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/Quadtree.cpp.s
.PHONY : GameEngine/src/Quadtree.cpp.s

GameEngine/src/RenderSystem.o: GameEngine/src/RenderSystem.cpp.o
.PHONY : GameEngine/src/RenderSystem.o

# target to build an object file
GameEngine/src/RenderSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/RenderSystem.cpp.o
.PHONY : GameEngine/src/RenderSystem.cpp.o

GameEngine/src/RenderSystem.i: GameEngine/src/RenderSystem.cpp.i
.PHONY : GameEngine/src/RenderSystem.i

# target to preprocess a source file
GameEngine/src/RenderSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/RenderSystem.cpp.i
.PHONY : GameEngine/src/RenderSystem.cpp.i

GameEngine/src/RenderSystem.s: GameEngine/src/RenderSystem.cpp.s
.PHONY : GameEngine/src/RenderSystem.s

# target to generate assembly for a file
GameEngine/src/RenderSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/RenderSystem.cpp.s
.PHONY : GameEngine/src/RenderSystem.cpp.s

GameEngine/src/SoundSystem.o: GameEngine/src/SoundSystem.cpp.o
.PHONY : GameEngine/src/SoundSystem.o

# target to build an object file
GameEngine/src/SoundSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/SoundSystem.cpp.o
.PHONY : GameEngine/src/SoundSystem.cpp.o

GameEngine/src/SoundSystem.i: GameEngine/src/SoundSystem.cpp.i
.PHONY : GameEngine/src/SoundSystem.i

# target to preprocess a source file
GameEngine/src/SoundSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/SoundSystem.cpp.i
.PHONY : GameEngine/src/SoundSystem.cpp.i

GameEngine/src/SoundSystem.s: GameEngine/src/SoundSystem.cpp.s
.PHONY : GameEngine/src/SoundSystem.s

# target to generate assembly for a file
GameEngine/src/SoundSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/SoundSystem.cpp.s
.PHONY : GameEngine/src/SoundSystem.cpp.s

GameEngine/src/SystemManager.o: GameEngine/src/SystemManager.cpp.o
.PHONY : GameEngine/src/SystemManager.o

# target to build an object file
GameEngine/src/SystemManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/SystemManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/SystemManager.cpp.o
.PHONY : GameEngine/src/SystemManager.cpp.o

GameEngine/src/SystemManager.i: GameEngine/src/SystemManager.cpp.i
.PHONY : GameEngine/src/SystemManager.i

# target to preprocess a source file
GameEngine/src/SystemManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/SystemManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/SystemManager.cpp.i
.PHONY : GameEngine/src/SystemManager.cpp.i

GameEngine/src/SystemManager.s: GameEngine/src/SystemManager.cpp.s
.PHONY : GameEngine/src/SystemManager.s

# target to generate assembly for a file
GameEngine/src/SystemManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/GameEngine/src/SystemManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/GameEngine/src/SystemManager.cpp.s
.PHONY : GameEngine/src/SystemManager.cpp.s

Server/src/network.o: Server/src/network.cpp.o
.PHONY : Server/src/network.o

# target to build an object file
Server/src/network.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network.cpp.o
.PHONY : Server/src/network.cpp.o

Server/src/network.i: Server/src/network.cpp.i
.PHONY : Server/src/network.i

# target to preprocess a source file
Server/src/network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network.cpp.i
.PHONY : Server/src/network.cpp.i

Server/src/network.s: Server/src/network.cpp.s
.PHONY : Server/src/network.s

# target to generate assembly for a file
Server/src/network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network.cpp.s
.PHONY : Server/src/network.cpp.s

Server/src/network_client_info.o: Server/src/network_client_info.cpp.o
.PHONY : Server/src/network_client_info.o

# target to build an object file
Server/src/network_client_info.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_client_info.cpp.o
.PHONY : Server/src/network_client_info.cpp.o

Server/src/network_client_info.i: Server/src/network_client_info.cpp.i
.PHONY : Server/src/network_client_info.i

# target to preprocess a source file
Server/src/network_client_info.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_client_info.cpp.i
.PHONY : Server/src/network_client_info.cpp.i

Server/src/network_client_info.s: Server/src/network_client_info.cpp.s
.PHONY : Server/src/network_client_info.s

# target to generate assembly for a file
Server/src/network_client_info.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_client_info.cpp.s
.PHONY : Server/src/network_client_info.cpp.s

Server/src/network_generate.o: Server/src/network_generate.cpp.o
.PHONY : Server/src/network_generate.o

# target to build an object file
Server/src/network_generate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_generate.cpp.o
.PHONY : Server/src/network_generate.cpp.o

Server/src/network_generate.i: Server/src/network_generate.cpp.i
.PHONY : Server/src/network_generate.i

# target to preprocess a source file
Server/src/network_generate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_generate.cpp.i
.PHONY : Server/src/network_generate.cpp.i

Server/src/network_generate.s: Server/src/network_generate.cpp.s
.PHONY : Server/src/network_generate.s

# target to generate assembly for a file
Server/src/network_generate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_generate.cpp.s
.PHONY : Server/src/network_generate.cpp.s

Server/src/network_lobby.o: Server/src/network_lobby.cpp.o
.PHONY : Server/src/network_lobby.o

# target to build an object file
Server/src/network_lobby.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_lobby.cpp.o
.PHONY : Server/src/network_lobby.cpp.o

Server/src/network_lobby.i: Server/src/network_lobby.cpp.i
.PHONY : Server/src/network_lobby.i

# target to preprocess a source file
Server/src/network_lobby.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_lobby.cpp.i
.PHONY : Server/src/network_lobby.cpp.i

Server/src/network_lobby.s: Server/src/network_lobby.cpp.s
.PHONY : Server/src/network_lobby.s

# target to generate assembly for a file
Server/src/network_lobby.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_lobby.cpp.s
.PHONY : Server/src/network_lobby.cpp.s

Server/src/network_server.o: Server/src/network_server.cpp.o
.PHONY : Server/src/network_server.o

# target to build an object file
Server/src/network_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_server.cpp.o
.PHONY : Server/src/network_server.cpp.o

Server/src/network_server.i: Server/src/network_server.cpp.i
.PHONY : Server/src/network_server.i

# target to preprocess a source file
Server/src/network_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_server.cpp.i
.PHONY : Server/src/network_server.cpp.i

Server/src/network_server.s: Server/src/network_server.cpp.s
.PHONY : Server/src/network_server.s

# target to generate assembly for a file
Server/src/network_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_server.cpp.s
.PHONY : Server/src/network_server.cpp.s

Server/src/network_update.o: Server/src/network_update.cpp.o
.PHONY : Server/src/network_update.o

# target to build an object file
Server/src/network_update.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_update.cpp.o
.PHONY : Server/src/network_update.cpp.o

Server/src/network_update.i: Server/src/network_update.cpp.i
.PHONY : Server/src/network_update.i

# target to preprocess a source file
Server/src/network_update.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_update.cpp.i
.PHONY : Server/src/network_update.cpp.i

Server/src/network_update.s: Server/src/network_update.cpp.s
.PHONY : Server/src/network_update.s

# target to generate assembly for a file
Server/src/network_update.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/network_update.cpp.s
.PHONY : Server/src/network_update.cpp.s

Server/src/protocol.o: Server/src/protocol.cpp.o
.PHONY : Server/src/protocol.o

# target to build an object file
Server/src/protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/protocol.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Server/src/protocol.cpp.o
.PHONY : Server/src/protocol.cpp.o

Server/src/protocol.i: Server/src/protocol.cpp.i
.PHONY : Server/src/protocol.i

# target to preprocess a source file
Server/src/protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/protocol.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Server/src/protocol.cpp.i
.PHONY : Server/src/protocol.cpp.i

Server/src/protocol.s: Server/src/protocol.cpp.s
.PHONY : Server/src/protocol.s

# target to generate assembly for a file
Server/src/protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/protocol.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/Server/src/protocol.cpp.s
.PHONY : Server/src/protocol.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... r-type_client"
	@echo "... r-type_server"
	@echo "... Client/src/AssetManager.o"
	@echo "... Client/src/AssetManager.i"
	@echo "... Client/src/AssetManager.s"
	@echo "... Client/src/NameEntryScreen.o"
	@echo "... Client/src/NameEntryScreen.i"
	@echo "... Client/src/NameEntryScreen.s"
	@echo "... Client/src/NetworkEntityMapper.o"
	@echo "... Client/src/NetworkEntityMapper.i"
	@echo "... Client/src/NetworkEntityMapper.s"
	@echo "... Client/src/Replay.o"
	@echo "... Client/src/Replay.i"
	@echo "... Client/src/Replay.s"
	@echo "... Client/src/SoloPlay.o"
	@echo "... Client/src/SoloPlay.i"
	@echo "... Client/src/SoloPlay.s"
	@echo "... Client/src/SoundManager.o"
	@echo "... Client/src/SoundManager.i"
	@echo "... Client/src/SoundManager.s"
	@echo "... Client/src/client.o"
	@echo "... Client/src/client.i"
	@echo "... Client/src/client.s"
	@echo "... Client/src/client2.o"
	@echo "... Client/src/client2.i"
	@echo "... Client/src/client2.s"
	@echo "... Client/src/client_init.o"
	@echo "... Client/src/client_init.i"
	@echo "... Client/src/client_init.s"
	@echo "... Client/src/client_network_part_one.o"
	@echo "... Client/src/client_network_part_one.i"
	@echo "... Client/src/client_network_part_one.s"
	@echo "... Client/src/client_network_part_two.o"
	@echo "... Client/src/client_network_part_two.i"
	@echo "... Client/src/client_network_part_two.s"
	@echo "... Client/src/client_protocol.o"
	@echo "... Client/src/client_protocol.i"
	@echo "... Client/src/client_protocol.s"
	@echo "... Client/src/client_replay.o"
	@echo "... Client/src/client_replay.i"
	@echo "... Client/src/client_replay.s"
	@echo "... Client/src/client_update.o"
	@echo "... Client/src/client_update.i"
	@echo "... Client/src/client_update.s"
	@echo "... Client/src/main.o"
	@echo "... Client/src/main.i"
	@echo "... Client/src/main.s"
	@echo "... Client/src/solo_play_render.o"
	@echo "... Client/src/solo_play_render.i"
	@echo "... Client/src/solo_play_render.s"
	@echo "... Core/src/Core.o"
	@echo "... Core/src/Core.i"
	@echo "... Core/src/Core.s"
	@echo "... GameEngine/src/AnimationSystem.o"
	@echo "... GameEngine/src/AnimationSystem.i"
	@echo "... GameEngine/src/AnimationSystem.s"
	@echo "... GameEngine/src/BossSystem.o"
	@echo "... GameEngine/src/BossSystem.i"
	@echo "... GameEngine/src/BossSystem.s"
	@echo "... GameEngine/src/CollectableSystem.o"
	@echo "... GameEngine/src/CollectableSystem.i"
	@echo "... GameEngine/src/CollectableSystem.s"
	@echo "... GameEngine/src/CollisionSystem.o"
	@echo "... GameEngine/src/CollisionSystem.i"
	@echo "... GameEngine/src/CollisionSystem.s"
	@echo "... GameEngine/src/ComponentManager.o"
	@echo "... GameEngine/src/ComponentManager.i"
	@echo "... GameEngine/src/ComponentManager.s"
	@echo "... GameEngine/src/EnemyBulletSystem.o"
	@echo "... GameEngine/src/EnemyBulletSystem.i"
	@echo "... GameEngine/src/EnemyBulletSystem.s"
	@echo "... GameEngine/src/EnemySystem.o"
	@echo "... GameEngine/src/EnemySystem.i"
	@echo "... GameEngine/src/EnemySystem.s"
	@echo "... GameEngine/src/EntityManager.o"
	@echo "... GameEngine/src/EntityManager.i"
	@echo "... GameEngine/src/EntityManager.s"
	@echo "... GameEngine/src/GameLogic.o"
	@echo "... GameEngine/src/GameLogic.i"
	@echo "... GameEngine/src/GameLogic.s"
	@echo "... GameEngine/src/LuaScript.o"
	@echo "... GameEngine/src/LuaScript.i"
	@echo "... GameEngine/src/LuaScript.s"
	@echo "... GameEngine/src/Mediator.o"
	@echo "... GameEngine/src/Mediator.i"
	@echo "... GameEngine/src/Mediator.s"
	@echo "... GameEngine/src/MovementSystem.o"
	@echo "... GameEngine/src/MovementSystem.i"
	@echo "... GameEngine/src/MovementSystem.s"
	@echo "... GameEngine/src/ObstacleSystem.o"
	@echo "... GameEngine/src/ObstacleSystem.i"
	@echo "... GameEngine/src/ObstacleSystem.s"
	@echo "... GameEngine/src/ProjectileSystem.o"
	@echo "... GameEngine/src/ProjectileSystem.i"
	@echo "... GameEngine/src/ProjectileSystem.s"
	@echo "... GameEngine/src/Quadtree.o"
	@echo "... GameEngine/src/Quadtree.i"
	@echo "... GameEngine/src/Quadtree.s"
	@echo "... GameEngine/src/RenderSystem.o"
	@echo "... GameEngine/src/RenderSystem.i"
	@echo "... GameEngine/src/RenderSystem.s"
	@echo "... GameEngine/src/SoundSystem.o"
	@echo "... GameEngine/src/SoundSystem.i"
	@echo "... GameEngine/src/SoundSystem.s"
	@echo "... GameEngine/src/SystemManager.o"
	@echo "... GameEngine/src/SystemManager.i"
	@echo "... GameEngine/src/SystemManager.s"
	@echo "... Server/src/network.o"
	@echo "... Server/src/network.i"
	@echo "... Server/src/network.s"
	@echo "... Server/src/network_client_info.o"
	@echo "... Server/src/network_client_info.i"
	@echo "... Server/src/network_client_info.s"
	@echo "... Server/src/network_generate.o"
	@echo "... Server/src/network_generate.i"
	@echo "... Server/src/network_generate.s"
	@echo "... Server/src/network_lobby.o"
	@echo "... Server/src/network_lobby.i"
	@echo "... Server/src/network_lobby.s"
	@echo "... Server/src/network_server.o"
	@echo "... Server/src/network_server.i"
	@echo "... Server/src/network_server.s"
	@echo "... Server/src/network_update.o"
	@echo "... Server/src/network_update.i"
	@echo "... Server/src/network_update.s"
	@echo "... Server/src/protocol.o"
	@echo "... Server/src/protocol.i"
	@echo "... Server/src/protocol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

